### ISSUE TITLE
[B1046题解]更新B1046题解Blog

### ISSUE THREAD

**Issue by QuakeWang** [OS-EDU/os-edu.github.io#13]
[B1046](https://github.com/OS-EDU/KO--CSP/pull/21)在KO--CSP中的pr已经提交完成，可以编写题目分析Blog

**Comment by freedom3219** [comment]
好的👌

**Comment by freedom3219** [comment]
已完成B1046题解Blog，提交pr地址如下：[B1046题解Blog](https://github.com/OS-EDU/os-edu.github.io/pull/12)
