### ISSUE TITLE
[PAT - B1011] 更新B1011. A + B 和 C 题解 Blog

### ISSUE THREAD

**Issue by QuakeWang** [OS-EDU/os-edu.github.io#16]
更新 PAT - B1011 . A + B 和 C 的相关讲解以及解题方法
[PAT - B1011 题目描述](https://github.com/OS-EDU/KO--CSP/blob/main/%E9%A2%98%E7%9B%AE%E6%8F%8F%E8%BF%B0/B1011.md)

**Comment by 2018DHY** [comment]
我来做这个任务

**Comment by QuakeWang** [comment]
已发布。[PAT_B1011](https://mp.weixin.qq.com/s/iDVifdPPAm2jrSUEIsWEoA)
